### ISSUE TITLE
Polyfill prevents newline in textareas.

### ISSUE THREAD

**Issue by svenvandescheur** [paulzi/form-association-polyfill#4]
When using the polypill the keypress event is listened to and prevented by the polypill for by it's inner workings. This prevents textarea's from adding newlines (tested on IE11)

Maybe the original event should not be prevented?

**Comment by paulzi** [comment]
Thank you! Fixed in v2.0.3.

**Comment by svenvandescheur** [comment]
Thanks for the quick fix, I can confirm this worked in IE11.
